# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import engine_pb2 as engine__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='com.cyb3rhq.api.engine.config',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63onfig.proto\x12\x1d\x63om.cyb3rhq.api.engine.config\x1a\x0c\x65ngine.proto\"0\n\x12RuntimeGet_Request\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"\x8b\x01\n\x13RuntimeGet_Response\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.com.cyb3rhq.api.engine.ReturnStatus\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_errorB\n\n\x08_content\"R\n\x12RuntimePut_Request\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\n\n\x08_content\"1\n\x13RuntimeSave_Request\x12\x11\n\x04path\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_pathb\x06proto3'
  ,
  dependencies=[engine__pb2.DESCRIPTOR,])




_RUNTIMEGET_REQUEST = _descriptor.Descriptor(
  name='RuntimeGet_Request',
  full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Request._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=61,
  serialized_end=109,
)


_RUNTIMEGET_RESPONSE = _descriptor.Descriptor(
  name='RuntimeGet_Response',
  full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Response.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Response._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_content', full_name='com.cyb3rhq.api.engine.config.RuntimeGet_Response._content',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=112,
  serialized_end=251,
)


_RUNTIMEPUT_REQUEST = _descriptor.Descriptor(
  name='RuntimePut_Request',
  full_name='com.cyb3rhq.api.engine.config.RuntimePut_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.cyb3rhq.api.engine.config.RuntimePut_Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.cyb3rhq.api.engine.config.RuntimePut_Request.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='com.cyb3rhq.api.engine.config.RuntimePut_Request._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_content', full_name='com.cyb3rhq.api.engine.config.RuntimePut_Request._content',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=253,
  serialized_end=335,
)


_RUNTIMESAVE_REQUEST = _descriptor.Descriptor(
  name='RuntimeSave_Request',
  full_name='com.cyb3rhq.api.engine.config.RuntimeSave_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='com.cyb3rhq.api.engine.config.RuntimeSave_Request.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_path', full_name='com.cyb3rhq.api.engine.config.RuntimeSave_Request._path',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=337,
  serialized_end=386,
)

_RUNTIMEGET_REQUEST.oneofs_by_name['_name'].fields.append(
  _RUNTIMEGET_REQUEST.fields_by_name['name'])
_RUNTIMEGET_REQUEST.fields_by_name['name'].containing_oneof = _RUNTIMEGET_REQUEST.oneofs_by_name['_name']
_RUNTIMEGET_RESPONSE.fields_by_name['status'].enum_type = engine__pb2._RETURNSTATUS
_RUNTIMEGET_RESPONSE.oneofs_by_name['_error'].fields.append(
  _RUNTIMEGET_RESPONSE.fields_by_name['error'])
_RUNTIMEGET_RESPONSE.fields_by_name['error'].containing_oneof = _RUNTIMEGET_RESPONSE.oneofs_by_name['_error']
_RUNTIMEGET_RESPONSE.oneofs_by_name['_content'].fields.append(
  _RUNTIMEGET_RESPONSE.fields_by_name['content'])
_RUNTIMEGET_RESPONSE.fields_by_name['content'].containing_oneof = _RUNTIMEGET_RESPONSE.oneofs_by_name['_content']
_RUNTIMEPUT_REQUEST.oneofs_by_name['_name'].fields.append(
  _RUNTIMEPUT_REQUEST.fields_by_name['name'])
_RUNTIMEPUT_REQUEST.fields_by_name['name'].containing_oneof = _RUNTIMEPUT_REQUEST.oneofs_by_name['_name']
_RUNTIMEPUT_REQUEST.oneofs_by_name['_content'].fields.append(
  _RUNTIMEPUT_REQUEST.fields_by_name['content'])
_RUNTIMEPUT_REQUEST.fields_by_name['content'].containing_oneof = _RUNTIMEPUT_REQUEST.oneofs_by_name['_content']
_RUNTIMESAVE_REQUEST.oneofs_by_name['_path'].fields.append(
  _RUNTIMESAVE_REQUEST.fields_by_name['path'])
_RUNTIMESAVE_REQUEST.fields_by_name['path'].containing_oneof = _RUNTIMESAVE_REQUEST.oneofs_by_name['_path']
DESCRIPTOR.message_types_by_name['RuntimeGet_Request'] = _RUNTIMEGET_REQUEST
DESCRIPTOR.message_types_by_name['RuntimeGet_Response'] = _RUNTIMEGET_RESPONSE
DESCRIPTOR.message_types_by_name['RuntimePut_Request'] = _RUNTIMEPUT_REQUEST
DESCRIPTOR.message_types_by_name['RuntimeSave_Request'] = _RUNTIMESAVE_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RuntimeGet_Request = _reflection.GeneratedProtocolMessageType('RuntimeGet_Request', (_message.Message,), {
  'DESCRIPTOR' : _RUNTIMEGET_REQUEST,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.config.RuntimeGet_Request)
  })
_sym_db.RegisterMessage(RuntimeGet_Request)

RuntimeGet_Response = _reflection.GeneratedProtocolMessageType('RuntimeGet_Response', (_message.Message,), {
  'DESCRIPTOR' : _RUNTIMEGET_RESPONSE,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.config.RuntimeGet_Response)
  })
_sym_db.RegisterMessage(RuntimeGet_Response)

RuntimePut_Request = _reflection.GeneratedProtocolMessageType('RuntimePut_Request', (_message.Message,), {
  'DESCRIPTOR' : _RUNTIMEPUT_REQUEST,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.config.RuntimePut_Request)
  })
_sym_db.RegisterMessage(RuntimePut_Request)

RuntimeSave_Request = _reflection.GeneratedProtocolMessageType('RuntimeSave_Request', (_message.Message,), {
  'DESCRIPTOR' : _RUNTIMESAVE_REQUEST,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.config.RuntimeSave_Request)
  })
_sym_db.RegisterMessage(RuntimeSave_Request)


# @@protoc_insertion_point(module_scope)
