# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engine.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='engine.proto',
  package='com.cyb3rhq.api.engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x65ngine.proto\x12\x16\x63om.cyb3rhq.api.engine\"l\n\x16GenericStatus_Response\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.com.cyb3rhq.api.engine.ReturnStatus\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error*.\n\x0cReturnStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3'
)

_RETURNSTATUS = _descriptor.EnumDescriptor(
  name='ReturnStatus',
  full_name='com.cyb3rhq.api.engine.ReturnStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_RETURNSTATUS)

ReturnStatus = enum_type_wrapper.EnumTypeWrapper(_RETURNSTATUS)
UNKNOWN = 0
OK = 1
ERROR = 2



_GENERICSTATUS_RESPONSE = _descriptor.Descriptor(
  name='GenericStatus_Response',
  full_name='com.cyb3rhq.api.engine.GenericStatus_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.cyb3rhq.api.engine.GenericStatus_Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='com.cyb3rhq.api.engine.GenericStatus_Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='com.cyb3rhq.api.engine.GenericStatus_Response._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=40,
  serialized_end=148,
)

_GENERICSTATUS_RESPONSE.fields_by_name['status'].enum_type = _RETURNSTATUS
_GENERICSTATUS_RESPONSE.oneofs_by_name['_error'].fields.append(
  _GENERICSTATUS_RESPONSE.fields_by_name['error'])
_GENERICSTATUS_RESPONSE.fields_by_name['error'].containing_oneof = _GENERICSTATUS_RESPONSE.oneofs_by_name['_error']
DESCRIPTOR.message_types_by_name['GenericStatus_Response'] = _GENERICSTATUS_RESPONSE
DESCRIPTOR.enum_types_by_name['ReturnStatus'] = _RETURNSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericStatus_Response = _reflection.GeneratedProtocolMessageType('GenericStatus_Response', (_message.Message,), {
  'DESCRIPTOR' : _GENERICSTATUS_RESPONSE,
  '__module__' : 'engine_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.GenericStatus_Response)
  })
_sym_db.RegisterMessage(GenericStatus_Response)


# @@protoc_insertion_point(module_scope)
