# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import engine_pb2 as engine__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geo.proto',
  package='com.cyb3rhq.api.engine.geo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tgeo.proto\x12\x1a\x63om.cyb3rhq.api.engine.geo\x1a\x0c\x65ngine.proto\"3\n\x07\x44\x62\x45ntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\",\n\x0e\x44\x62Post_Request\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\" \n\x10\x44\x62\x44\x65lete_Request\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x10\n\x0e\x44\x62List_Request\"\x9b\x01\n\x0f\x44\x62List_Response\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.com.cyb3rhq.api.engine.ReturnStatus\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x34\n\x07\x65ntries\x18\x03 \x03(\x0b\x32#.com.cyb3rhq.api.engine.geo.DbEntryB\x08\n\x06_error\"T\n\x16\x44\x62RemoteUpsert_Request\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05\x64\x62Url\x18\x03 \x01(\t\x12\x0f\n\x07hashUrl\x18\x04 \x01(\tb\x06proto3'
  ,
  dependencies=[engine__pb2.DESCRIPTOR,])




_DBENTRY = _descriptor.Descriptor(
  name='DbEntry',
  full_name='com.cyb3rhq.api.engine.geo.DbEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.cyb3rhq.api.engine.geo.DbEntry.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='com.cyb3rhq.api.engine.geo.DbEntry.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyb3rhq.api.engine.geo.DbEntry.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=106,
)


_DBPOST_REQUEST = _descriptor.Descriptor(
  name='DbPost_Request',
  full_name='com.cyb3rhq.api.engine.geo.DbPost_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='com.cyb3rhq.api.engine.geo.DbPost_Request.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyb3rhq.api.engine.geo.DbPost_Request.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=152,
)


_DBDELETE_REQUEST = _descriptor.Descriptor(
  name='DbDelete_Request',
  full_name='com.cyb3rhq.api.engine.geo.DbDelete_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='com.cyb3rhq.api.engine.geo.DbDelete_Request.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=186,
)


_DBLIST_REQUEST = _descriptor.Descriptor(
  name='DbList_Request',
  full_name='com.cyb3rhq.api.engine.geo.DbList_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=204,
)


_DBLIST_RESPONSE = _descriptor.Descriptor(
  name='DbList_Response',
  full_name='com.cyb3rhq.api.engine.geo.DbList_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.cyb3rhq.api.engine.geo.DbList_Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='com.cyb3rhq.api.engine.geo.DbList_Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entries', full_name='com.cyb3rhq.api.engine.geo.DbList_Response.entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='com.cyb3rhq.api.engine.geo.DbList_Response._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=207,
  serialized_end=362,
)


_DBREMOTEUPSERT_REQUEST = _descriptor.Descriptor(
  name='DbRemoteUpsert_Request',
  full_name='com.cyb3rhq.api.engine.geo.DbRemoteUpsert_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='com.cyb3rhq.api.engine.geo.DbRemoteUpsert_Request.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyb3rhq.api.engine.geo.DbRemoteUpsert_Request.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbUrl', full_name='com.cyb3rhq.api.engine.geo.DbRemoteUpsert_Request.dbUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hashUrl', full_name='com.cyb3rhq.api.engine.geo.DbRemoteUpsert_Request.hashUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=448,
)

_DBLIST_RESPONSE.fields_by_name['status'].enum_type = engine__pb2._RETURNSTATUS
_DBLIST_RESPONSE.fields_by_name['entries'].message_type = _DBENTRY
_DBLIST_RESPONSE.oneofs_by_name['_error'].fields.append(
  _DBLIST_RESPONSE.fields_by_name['error'])
_DBLIST_RESPONSE.fields_by_name['error'].containing_oneof = _DBLIST_RESPONSE.oneofs_by_name['_error']
DESCRIPTOR.message_types_by_name['DbEntry'] = _DBENTRY
DESCRIPTOR.message_types_by_name['DbPost_Request'] = _DBPOST_REQUEST
DESCRIPTOR.message_types_by_name['DbDelete_Request'] = _DBDELETE_REQUEST
DESCRIPTOR.message_types_by_name['DbList_Request'] = _DBLIST_REQUEST
DESCRIPTOR.message_types_by_name['DbList_Response'] = _DBLIST_RESPONSE
DESCRIPTOR.message_types_by_name['DbRemoteUpsert_Request'] = _DBREMOTEUPSERT_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbEntry = _reflection.GeneratedProtocolMessageType('DbEntry', (_message.Message,), {
  'DESCRIPTOR' : _DBENTRY,
  '__module__' : 'geo_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.geo.DbEntry)
  })
_sym_db.RegisterMessage(DbEntry)

DbPost_Request = _reflection.GeneratedProtocolMessageType('DbPost_Request', (_message.Message,), {
  'DESCRIPTOR' : _DBPOST_REQUEST,
  '__module__' : 'geo_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.geo.DbPost_Request)
  })
_sym_db.RegisterMessage(DbPost_Request)

DbDelete_Request = _reflection.GeneratedProtocolMessageType('DbDelete_Request', (_message.Message,), {
  'DESCRIPTOR' : _DBDELETE_REQUEST,
  '__module__' : 'geo_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.geo.DbDelete_Request)
  })
_sym_db.RegisterMessage(DbDelete_Request)

DbList_Request = _reflection.GeneratedProtocolMessageType('DbList_Request', (_message.Message,), {
  'DESCRIPTOR' : _DBLIST_REQUEST,
  '__module__' : 'geo_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.geo.DbList_Request)
  })
_sym_db.RegisterMessage(DbList_Request)

DbList_Response = _reflection.GeneratedProtocolMessageType('DbList_Response', (_message.Message,), {
  'DESCRIPTOR' : _DBLIST_RESPONSE,
  '__module__' : 'geo_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.geo.DbList_Response)
  })
_sym_db.RegisterMessage(DbList_Response)

DbRemoteUpsert_Request = _reflection.GeneratedProtocolMessageType('DbRemoteUpsert_Request', (_message.Message,), {
  'DESCRIPTOR' : _DBREMOTEUPSERT_REQUEST,
  '__module__' : 'geo_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.geo.DbRemoteUpsert_Request)
  })
_sym_db.RegisterMessage(DbRemoteUpsert_Request)


# @@protoc_insertion_point(module_scope)
