# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import engine_pb2 as engine__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph.proto',
  package='com.cyb3rhq.api.engine.graph',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgraph.proto\x12\x1c\x63om.cyb3rhq.api.engine.graph\x1a\x0c\x65ngine.proto\"N\n\x10GraphGet_Request\x12\x13\n\x06policy\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04type\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_policyB\x07\n\x05_type\"\x89\x01\n\x11GraphGet_Response\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.com.cyb3rhq.api.engine.ReturnStatus\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_errorB\n\n\x08_contentb\x06proto3'
  ,
  dependencies=[engine__pb2.DESCRIPTOR,])




_GRAPHGET_REQUEST = _descriptor.Descriptor(
  name='GraphGet_Request',
  full_name='com.cyb3rhq.api.engine.graph.GraphGet_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Request.policy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Request.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_policy', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Request._policy',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Request._type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=137,
)


_GRAPHGET_RESPONSE = _descriptor.Descriptor(
  name='GraphGet_Response',
  full_name='com.cyb3rhq.api.engine.graph.GraphGet_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Response.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Response._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_content', full_name='com.cyb3rhq.api.engine.graph.GraphGet_Response._content',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=140,
  serialized_end=277,
)

_GRAPHGET_REQUEST.oneofs_by_name['_policy'].fields.append(
  _GRAPHGET_REQUEST.fields_by_name['policy'])
_GRAPHGET_REQUEST.fields_by_name['policy'].containing_oneof = _GRAPHGET_REQUEST.oneofs_by_name['_policy']
_GRAPHGET_REQUEST.oneofs_by_name['_type'].fields.append(
  _GRAPHGET_REQUEST.fields_by_name['type'])
_GRAPHGET_REQUEST.fields_by_name['type'].containing_oneof = _GRAPHGET_REQUEST.oneofs_by_name['_type']
_GRAPHGET_RESPONSE.fields_by_name['status'].enum_type = engine__pb2._RETURNSTATUS
_GRAPHGET_RESPONSE.oneofs_by_name['_error'].fields.append(
  _GRAPHGET_RESPONSE.fields_by_name['error'])
_GRAPHGET_RESPONSE.fields_by_name['error'].containing_oneof = _GRAPHGET_RESPONSE.oneofs_by_name['_error']
_GRAPHGET_RESPONSE.oneofs_by_name['_content'].fields.append(
  _GRAPHGET_RESPONSE.fields_by_name['content'])
_GRAPHGET_RESPONSE.fields_by_name['content'].containing_oneof = _GRAPHGET_RESPONSE.oneofs_by_name['_content']
DESCRIPTOR.message_types_by_name['GraphGet_Request'] = _GRAPHGET_REQUEST
DESCRIPTOR.message_types_by_name['GraphGet_Response'] = _GRAPHGET_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphGet_Request = _reflection.GeneratedProtocolMessageType('GraphGet_Request', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHGET_REQUEST,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.graph.GraphGet_Request)
  })
_sym_db.RegisterMessage(GraphGet_Request)

GraphGet_Response = _reflection.GeneratedProtocolMessageType('GraphGet_Response', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHGET_RESPONSE,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:com.cyb3rhq.api.engine.graph.GraphGet_Response)
  })
_sym_db.RegisterMessage(GraphGet_Response)


# @@protoc_insertion_point(module_scope)
